# .github/workflows/build-mini-app.yml
name: Build, Push & Deploy Mini-App to GHCR

on:
  push:
    paths:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: vars
        run: |
          echo "app_id=$(jq -r .appId mini-app-template/manifest.json)" >> $GITHUB_OUTPUT
          echo "version=$(jq -r .version mini-app-template/manifest.json)" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Docker image to GHCR
        shell: bash
        run: |
          OWNER="${{ github.repository_owner }}"
          OWNER_LOWER=$(echo "$OWNER" | tr '[:upper:]' '[:lower:]')
          APP="${{ steps.vars.outputs.app_id }}"
          VER="${{ steps.vars.outputs.version }}"
          IMAGE="ghcr.io/${OWNER_LOWER}/lex-app-plugins/${APP}"
          echo "Building and pushing $IMAGE:$VER and $IMAGE:latest"
          docker buildx build \
            --push \
            --tag "$IMAGE:$VER" \
            --tag "$IMAGE:latest" \
            mini-app-template

      - name: Set up kubeconfig
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        env:
          IMAGE: ghcr.io/${{ github.repository_owner }}/lex-app-plugins/${{ steps.vars.outputs.app_id }}:${{ steps.vars.outputs.version }}
        run: |
          sed "s|IMAGE_PLACEHOLDER|$IMAGE|" k8s-deployment.yml > k8s.yml
          kubectl apply -f k8s.yml
