# .github/workflows/build-mini-app.yml
name: Build & Push Mini-App to GHCR

on:
  push:
    paths:
      - 'mini-app-template/manifest.json'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: vars
        run: |
          echo "app_id=$(jq -r .appId mini-app-template/manifest.json)" >> $GITHUB_OUTPUT
          echo "version=$(jq -r .version mini-app-template/manifest.json)" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Docker image to GHCR
        shell: bash
        run: |
          # lowercase the owner (Docker tags must be lowercase)
          OWNER="${{ github.repository_owner }}"
          OWNER_LOWER=$(echo "$OWNER" | tr '[:upper:]' '[:lower:]')
          APP="${{ steps.vars.outputs.app_id }}"
          VER="${{ steps.vars.outputs.version }}"

          IMAGE="ghcr.io/${OWNER_LOWER}/lex-app-plugins/${APP}"

          echo "Building and pushing $IMAGE:$VER and $IMAGE:latest"
          docker buildx build \
            --push \
            --tag "$IMAGE:$VER" \
            --tag "$IMAGE:latest" \
            mini-app-template
