name: Build & Push Mini-App to GHCR

on:
  push:
    paths:
      - 'mini-app-template/manifest.json'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your code
      - uses: actions/checkout@v3

      # 2. Extract appId & version
      - id: vars
        run: |
          echo "app_id=$(jq -r .appId mini-app-template/manifest.json)" >> $GITHUB_OUTPUT
          echo "version=$(jq -r .version mini-app-template/manifest.json)" >> $GITHUB_OUTPUT

      # 3. Log in to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Build & push
      - name: Build & push Docker image to GHCR
        uses: docker/build-push-action@v3
        with:
          context: mini-app-template
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/lex-app-plugins/${{ steps.vars.outputs.app_id }}:${{ steps.vars.outputs.version }}
            ghcr.io/${{ github.repository_owner }}/lex-app-plugins/${{ steps.vars.outputs.app_id }}:latest
