name: Docker Build for mini-app-template

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_NAME: mini-app-template
  APP_FOLDER: mini-app-template
  PUSH_IMAGE: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        if: env.PUSH_IMAGE == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.APP_FOLDER }}
          push: ${{ env.PUSH_IMAGE }}
          tags: ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
